### ISSUE TITLE
Indipendent entities, SOLID Interfaces

### ISSUE THREAD

**Issue by mbunge** [phpthinktank/blast-orm#7]
To hopefully provide some constructive feedback to expand on /u/drgomesp's comment:
I really prefer that my entities are fully independent from the ORM and having to extend the ORM's entity class makes that impossible. I would want something like this:

``` php
class ElectionResult
{
    /* business/domain logic */
}
```

A repository interface:

``` php
interface ElectionResultRepository
{
    /**
     * @param int $id
     * @return ElectionResult|null
     */
    public function findById($id)
}
```

And an implementation that returns a implementation-specific subclass of ElectionResult that doesn't break the Liskov Substitution Principle.

``` php
class BlastElectionResultRepository implements ElectionResultRepository
{

    public function findById($id)
    {
        return $this->mapper->find($id);
    }

}
```

I do see that you have an EntityInterface and EntityTrait, which is a good first step, but the interface has still has 20ish methods, including __get, __set, __isset, and __call, which almost invalidates using an interface in the first place. I'd much, much prefer a lean interface where the entity just has to pass it's data to a configured mapper class. Something like this, for example:

``` php
interface EntityInterface
{
    /**
      * @return array
      */
    public function getDataForMapper();

    /**
      * @return array
      */
    public function getRelationsForMapper();
}
```

That being said, if you think it's something that might be feasible, I may be able to throw together something for a pull request under a different interface, maybe PlainEntityInterface or something similar. Regardless, I hope this feedback is valuable!

**Comment by wolfy-j** [comment]
Hi, sorry for bothering, what about making MapperHelper (your last commits) an object dependency for Mapper, in this case it can be used as runtime cache for your schemas and provide better test base for mapper compared to static calls.

**Comment by mbunge** [comment]
I the helper concept will be removed since I decide to use an adapter for my entity classes. I plan to implement an runtime cache for entity adapters with #9
