### ISSUE TITLE
Seperate schema definitions from entity

### ISSUE THREAD

**Issue by mbunge** [phpthinktank/blast-orm#8]
This:

``` php
class Post extends AbstractEntity
{

  /**
   * Configure entity
   */
  public function configure()
  {
      $table = new Table('post');
      $table->addColumn('id', Type::INTEGER)
          ->setAutoincrement(true)
          ->setLength(10);
      $table->addColumn('title', Type::STRING);
      $table->addColumn('content', Type::TEXT);
      $table->addColumn('date', Type::DATETIME)
          ->setDefault(new \DateTime());
      $table->setPrimaryKey(['id']);

      //set entity table
      $this->setTable($table);
  }
}
```

Feels wrong. Like not the syntax the class naming. First of all, maybe I am miss understanding something, and feel free to tell me.
it should go: Migration -> Model -> Entity. as In we create a migration to create a new table, we create a model for that table and then we create an entity that extends the model.
You are extending an entity (abstract) and creating a table (??)
The way I understand it is: Migrations create the tables, Models know of the relation ships, table fields and do the "find or create" and the scopes (laravel) where as entities, least the way we use them, are classes that do the joins and the wheres and the get/set jazz (we use active record so no need for getters and setters)

**Comment by wolfy-j** [comment]
I'v been solving similar issue in my ORM and ended with following idea:
1) Entity declares needed schema in internal DSL, in your case it can be something like:

``` php
 public static function declare()
  {
      $declaration= new Declaration('post');
      $declaration->requireColumn('id', Type::INTEGER)
          ->setAutoincrement(true)
          ->setLength(10);
      $declaration->requireColumn('title', Type::STRING);
      $declaration->requireColumn('content', Type::TEXT);
      $declaration->requireColumn('date', Type::DATETIME)
          ->setDefault(new \DateTime());
      $declaration->setPrimaryKey(['id']);

      //set entity table
      return $declaration;
  }
```

2) ORM grabs declaration from known entities and generates set of needed migrations (based on DIFF)
3) Migrations run - schema is synced

> Extending becomes super easy as you can inherit parent declaration.

On a practice you only need to read this declaration once and later cache it either in some file or via code generation.

**Comment by wolfy-j** [comment]
In my case i mixed both relation and table declarations in one place which is read at moment of schema generation via static analysis (schemas are pretty compact as result):

``` php
class Post extends Record
{
    use TimestampsTrait;

    protected $database = 'blog';

    protected $schema = [
        'id'     => 'bigPrimary',
        'title'  => 'string(64)',
        'status' => 'enum(published,draft)',
        'body'   => 'text',

        'author'   => [self::BELONGS_TO => Author::class],
        'comments' => [self::HAS_MANY => Comment::class],

        'collaborators' => [
            self::MANY_TO_MANY  => User::class,
            self::PIVOT_TABLE   => 'post_collaborators_map',
            self::PIVOT_COLUMNS => [
                'time_assigned' => 'datetime',
                'type'          => 'string, nullable',
            ],
            User::INVERSE       => 'collaborated_posts'
        ],
    ];
}
```

**Comment by mbunge** [comment]
Entity adapters made definitions accessible from entity classes or generate them if entity class has no definition.

e.g

Entity definition

``` php
<?php

namespace App\Entities;

class Post {

}
```

Accessing table and primarykey

``` php

$post = new App\Entities\Post;
$postAdapter = new EntityAdapter($post);

$postAdapter->getTableName() //post
$postAdapter->getPrimaryKeyName() //id
```

More intelligent definition features will be added soon in upcoming releases.
